/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.18.dev138
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CompanySensorGetResponse200Category,
    CompanySensorGetResponse200CategoryFromJSON,
    CompanySensorGetResponse200CategoryFromJSONTyped,
    CompanySensorGetResponse200CategoryToJSON,
} from './';

/**
 * Сведения о датчике
 * @export
 * @interface CompanySensorGetResponse200
 */
export interface CompanySensorGetResponse200 {
    /**
     * Идентификатор датчика
     * @type {number}
     * @memberof CompanySensorGetResponse200
     */
    id: number;
    /**
     * Код датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200
     */
    code: string;
    /**
     * Краткое название датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200
     */
    name: string;
    /**
     * Описание датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200
     */
    description: string;
    /**
     * Отображаемая площадка по умолчанию
     * @type {boolean}
     * @memberof CompanySensorGetResponse200
     */
    byDefault: boolean;
    /**
     * Идентификатор компании
     * @type {number}
     * @memberof CompanySensorGetResponse200
     */
    companyId: number;
    /**
     * Идентификатор площадки
     * @type {number}
     * @memberof CompanySensorGetResponse200
     */
    locationId?: number;
    /**
     * Расположение датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200
     */
    address?: string;
    /**
     * Адрес видеопотока
     * @type {string}
     * @memberof CompanySensorGetResponse200
     */
    url?: string;
    /**
     * 
     * @type {CompanySensorGetResponse200Category}
     * @memberof CompanySensorGetResponse200
     */
    category: CompanySensorGetResponse200Category;
}

export function CompanySensorGetResponse200FromJSON(json: any): CompanySensorGetResponse200 {
    return CompanySensorGetResponse200FromJSONTyped(json, false);
}

export function CompanySensorGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanySensorGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'description': json['description'],
        'byDefault': json['by_default'],
        'companyId': json['company_id'],
        'locationId': !exists(json, 'location_id') ? undefined : json['location_id'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'category': CompanySensorGetResponse200CategoryFromJSON(json['category']),
    };
}

export function CompanySensorGetResponse200ToJSON(value?: CompanySensorGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'name': value.name,
        'description': value.description,
        'by_default': value.byDefault,
        'company_id': value.companyId,
        'location_id': value.locationId,
        'address': value.address,
        'url': value.url,
        'category': CompanySensorGetResponse200CategoryToJSON(value.category),
    };
}


