/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev148
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CompanySensorGetResponse200RefCategory,
    CompanySensorGetResponse200RefCategoryFromJSON,
    CompanySensorGetResponse200RefCategoryFromJSONTyped,
    CompanySensorGetResponse200RefCategoryToJSON,
} from './';

/**
 * Редко изменяемые справочные данные датчика
 * @export
 * @interface CompanySensorGetResponse200Ref
 */
export interface CompanySensorGetResponse200Ref {
    /**
     * Идентификатор датчика
     * @type {number}
     * @memberof CompanySensorGetResponse200Ref
     */
    id: number;
    /**
     * Код датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200Ref
     */
    code: string;
    /**
     * Краткое название датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200Ref
     */
    name: string;
    /**
     * Описание датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200Ref
     */
    description: string;
    /**
     * Отображаемая площадка по умолчанию
     * @type {boolean}
     * @memberof CompanySensorGetResponse200Ref
     */
    byDefault: boolean;
    /**
     * Идентификатор компании
     * @type {number}
     * @memberof CompanySensorGetResponse200Ref
     */
    companyId: number;
    /**
     * Идентификатор площадки
     * @type {number}
     * @memberof CompanySensorGetResponse200Ref
     */
    locationId: number;
    /**
     * Расположение датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200Ref
     */
    address: string;
    /**
     * Адрес видеопотока
     * @type {string}
     * @memberof CompanySensorGetResponse200Ref
     */
    url: string;
    /**
     * 
     * @type {CompanySensorGetResponse200RefCategory}
     * @memberof CompanySensorGetResponse200Ref
     */
    category: CompanySensorGetResponse200RefCategory;
}

export function CompanySensorGetResponse200RefFromJSON(json: any): CompanySensorGetResponse200Ref {
    return CompanySensorGetResponse200RefFromJSONTyped(json, false);
}

export function CompanySensorGetResponse200RefFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanySensorGetResponse200Ref {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'description': json['description'],
        'byDefault': json['by_default'],
        'companyId': json['company_id'],
        'locationId': json['location_id'],
        'address': json['address'],
        'url': json['url'],
        'category': CompanySensorGetResponse200RefCategoryFromJSON(json['category']),
    };
}

export function CompanySensorGetResponse200RefToJSON(value?: CompanySensorGetResponse200Ref | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'name': value.name,
        'description': value.description,
        'by_default': value.byDefault,
        'company_id': value.companyId,
        'location_id': value.locationId,
        'address': value.address,
        'url': value.url,
        'category': CompanySensorGetResponse200RefCategoryToJSON(value.category),
    };
}


