/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.16.dev115
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PipelinesGetResponse200Pipelines,
    PipelinesGetResponse200PipelinesFromJSON,
    PipelinesGetResponse200PipelinesFromJSONTyped,
    PipelinesGetResponse200PipelinesToJSON,
} from './';

/**
 * 
 * @export
 * @interface CompanyPipelineGetResponse200
 */
export interface CompanyPipelineGetResponse200 {
    /**
     * 
     * @type {PipelinesGetResponse200Pipelines}
     * @memberof CompanyPipelineGetResponse200
     */
    pipeline: PipelinesGetResponse200Pipelines;
}

export function CompanyPipelineGetResponse200FromJSON(json: any): CompanyPipelineGetResponse200 {
    return CompanyPipelineGetResponse200FromJSONTyped(json, false);
}

export function CompanyPipelineGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyPipelineGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pipeline': PipelinesGetResponse200PipelinesFromJSON(json['pipeline']),
    };
}

export function CompanyPipelineGetResponse200ToJSON(value?: CompanyPipelineGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pipeline': PipelinesGetResponse200PipelinesToJSON(value.pipeline),
    };
}


