/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev156
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CompanySensorStatsGetResponse200Stats,
    CompanySensorStatsGetResponse200StatsFromJSON,
    CompanySensorStatsGetResponse200StatsFromJSONTyped,
    CompanySensorStatsGetResponse200StatsToJSON,
} from './';

/**
 * 
 * @export
 * @interface CompanySensorStatsGetResponse200
 */
export interface CompanySensorStatsGetResponse200 {
    /**
     * Статистические показатели
     * @type {Array<CompanySensorStatsGetResponse200Stats>}
     * @memberof CompanySensorStatsGetResponse200
     */
    stats: Array<CompanySensorStatsGetResponse200Stats>;
}

export function CompanySensorStatsGetResponse200FromJSON(json: any): CompanySensorStatsGetResponse200 {
    return CompanySensorStatsGetResponse200FromJSONTyped(json, false);
}

export function CompanySensorStatsGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanySensorStatsGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stats': ((json['stats'] as Array<any>).map(CompanySensorStatsGetResponse200StatsFromJSON)),
    };
}

export function CompanySensorStatsGetResponse200ToJSON(value?: CompanySensorStatsGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stats': ((value.stats as Array<any>).map(CompanySensorStatsGetResponse200StatsToJSON)),
    };
}


