/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev160
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CompanyPipelinesPostRequestConf,
    CompanyPipelinesPostRequestConfFromJSON,
    CompanyPipelinesPostRequestConfFromJSONTyped,
    CompanyPipelinesPostRequestConfToJSON,
} from './';

/**
 * 
 * @export
 * @interface CompanyPipelinesPostRequest
 */
export interface CompanyPipelinesPostRequest {
    /**
     * Название конвейера
     * @type {string}
     * @memberof CompanyPipelinesPostRequest
     */
    name: string;
    /**
     * Описание конвейера
     * @type {string}
     * @memberof CompanyPipelinesPostRequest
     */
    description: string;
    /**
     * 
     * @type {CompanyPipelinesPostRequestConf}
     * @memberof CompanyPipelinesPostRequest
     */
    conf: CompanyPipelinesPostRequestConf;
}

export function CompanyPipelinesPostRequestFromJSON(json: any): CompanyPipelinesPostRequest {
    return CompanyPipelinesPostRequestFromJSONTyped(json, false);
}

export function CompanyPipelinesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyPipelinesPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'conf': CompanyPipelinesPostRequestConfFromJSON(json['conf']),
    };
}

export function CompanyPipelinesPostRequestToJSON(value?: CompanyPipelinesPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'conf': CompanyPipelinesPostRequestConfToJSON(value.conf),
    };
}


