/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev156
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Редко изменяемые справочные данные датчика
 * @export
 * @interface CompanySensorGetResponse200Ref
 */
export interface CompanySensorGetResponse200Ref {
    /**
     * Расположение датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200Ref
     */
    address: string;
    /**
     * Код датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200Ref
     */
    code: string;
    /**
     * Идентификатор компании
     * @type {number}
     * @memberof CompanySensorGetResponse200Ref
     */
    companyId: number;
    /**
     * Описание датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200Ref
     */
    description: string;
    /**
     * Идентификатор датчика
     * @type {number}
     * @memberof CompanySensorGetResponse200Ref
     */
    id: number;
    /**
     * Идентификатор площадки
     * @type {number}
     * @memberof CompanySensorGetResponse200Ref
     */
    locationId: number;
    /**
     * Краткое название датчика
     * @type {string}
     * @memberof CompanySensorGetResponse200Ref
     */
    name: string;
    /**
     * Адрес видеопотока
     * @type {string}
     * @memberof CompanySensorGetResponse200Ref
     */
    url: string;
}

export function CompanySensorGetResponse200RefFromJSON(json: any): CompanySensorGetResponse200Ref {
    return CompanySensorGetResponse200RefFromJSONTyped(json, false);
}

export function CompanySensorGetResponse200RefFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanySensorGetResponse200Ref {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'code': json['code'],
        'companyId': json['company_id'],
        'description': json['description'],
        'id': json['id'],
        'locationId': json['location_id'],
        'name': json['name'],
        'url': json['url'],
    };
}

export function CompanySensorGetResponse200RefToJSON(value?: CompanySensorGetResponse200Ref | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'code': value.code,
        'company_id': value.companyId,
        'description': value.description,
        'id': value.id,
        'location_id': value.locationId,
        'name': value.name,
        'url': value.url,
    };
}


