/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.18.dev141
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CompanySensorGetResponse200Ref,
    CompanySensorGetResponse200RefFromJSON,
    CompanySensorGetResponse200RefFromJSONTyped,
    CompanySensorGetResponse200RefToJSON,
    CompanySensorGetResponse200Status,
    CompanySensorGetResponse200StatusFromJSON,
    CompanySensorGetResponse200StatusFromJSONTyped,
    CompanySensorGetResponse200StatusToJSON,
} from './';

/**
 * Сведения о датчике
 * @export
 * @interface CompanySensorGetResponse200
 */
export interface CompanySensorGetResponse200 {
    /**
     * 
     * @type {CompanySensorGetResponse200Ref}
     * @memberof CompanySensorGetResponse200
     */
    ref: CompanySensorGetResponse200Ref;
    /**
     * 
     * @type {CompanySensorGetResponse200Status}
     * @memberof CompanySensorGetResponse200
     */
    status: CompanySensorGetResponse200Status;
    /**
     * Метрики датчика
     * @type {object}
     * @memberof CompanySensorGetResponse200
     */
    metrics: object;
}

export function CompanySensorGetResponse200FromJSON(json: any): CompanySensorGetResponse200 {
    return CompanySensorGetResponse200FromJSONTyped(json, false);
}

export function CompanySensorGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanySensorGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ref': CompanySensorGetResponse200RefFromJSON(json['ref']),
        'status': CompanySensorGetResponse200StatusFromJSON(json['status']),
        'metrics': json['metrics'],
    };
}

export function CompanySensorGetResponse200ToJSON(value?: CompanySensorGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ref': CompanySensorGetResponse200RefToJSON(value.ref),
        'status': CompanySensorGetResponse200StatusToJSON(value.status),
        'metrics': value.metrics,
    };
}


