/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev153
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Сведения о площадке
 * @export
 * @interface CompanyLocationsGetResponse200Locations
 */
export interface CompanyLocationsGetResponse200Locations {
    /**
     * Идентификатор площадки
     * @type {number}
     * @memberof CompanyLocationsGetResponse200Locations
     */
    id: number;
    /**
     * Код площадки
     * @type {string}
     * @memberof CompanyLocationsGetResponse200Locations
     */
    code: string;
    /**
     * Краткое название площадки
     * @type {string}
     * @memberof CompanyLocationsGetResponse200Locations
     */
    name: string;
    /**
     * Описание площадки
     * @type {string}
     * @memberof CompanyLocationsGetResponse200Locations
     */
    description: string;
    /**
     * Идентификатор компании
     * @type {number}
     * @memberof CompanyLocationsGetResponse200Locations
     */
    companyId: number;
}

export function CompanyLocationsGetResponse200LocationsFromJSON(json: any): CompanyLocationsGetResponse200Locations {
    return CompanyLocationsGetResponse200LocationsFromJSONTyped(json, false);
}

export function CompanyLocationsGetResponse200LocationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyLocationsGetResponse200Locations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'description': json['description'],
        'companyId': json['company_id'],
    };
}

export function CompanyLocationsGetResponse200LocationsToJSON(value?: CompanyLocationsGetResponse200Locations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'name': value.name,
        'description': value.description,
        'company_id': value.companyId,
    };
}


