/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.16.dev115
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Превью изображения по событию
 * @export
 * @interface EventsGetResponse200Thumbnail
 */
export interface EventsGetResponse200Thumbnail {
    /**
     * Идентификатор превью изображения
     * @type {number}
     * @memberof EventsGetResponse200Thumbnail
     */
    id: number;
    /**
     * Идентификатор категории превью
     * @type {number}
     * @memberof EventsGetResponse200Thumbnail
     */
    categoryId: number;
    /**
     * Идентификатор изображения
     * @type {number}
     * @memberof EventsGetResponse200Thumbnail
     */
    imageId: number;
    /**
     * Формат изображения
     * @type {string}
     * @memberof EventsGetResponse200Thumbnail
     */
    compression: string;
    /**
     * Содержимое изображения в формате Base64
     * @type {string}
     * @memberof EventsGetResponse200Thumbnail
     */
    content: string;
}

export function EventsGetResponse200ThumbnailFromJSON(json: any): EventsGetResponse200Thumbnail {
    return EventsGetResponse200ThumbnailFromJSONTyped(json, false);
}

export function EventsGetResponse200ThumbnailFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsGetResponse200Thumbnail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'categoryId': json['category_id'],
        'imageId': json['image_id'],
        'compression': json['compression'],
        'content': json['content'],
    };
}

export function EventsGetResponse200ThumbnailToJSON(value?: EventsGetResponse200Thumbnail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'category_id': value.categoryId,
        'image_id': value.imageId,
        'compression': value.compression,
        'content': value.content,
    };
}


