/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev153
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EventsGetResponse200ImageTrackBoxes,
    EventsGetResponse200ImageTrackBoxesFromJSON,
    EventsGetResponse200ImageTrackBoxesFromJSONTyped,
    EventsGetResponse200ImageTrackBoxesToJSON,
} from './';

/**
 * Сведения об изображении
 * @export
 * @interface EventsGetResponse200Image
 */
export interface EventsGetResponse200Image {
    /**
     * Идентификатор изображения
     * @type {number}
     * @memberof EventsGetResponse200Image
     */
    id: number;
    /**
     * Формат изображения
     * @type {string}
     * @memberof EventsGetResponse200Image
     */
    compression: string;
    /**
     * Ширина изображения
     * @type {number}
     * @memberof EventsGetResponse200Image
     */
    width: number;
    /**
     * Высота изображения
     * @type {number}
     * @memberof EventsGetResponse200Image
     */
    height: number;
    /**
     * Разметка обнаруженных объектов
     * @type {Array<EventsGetResponse200ImageTrackBoxes>}
     * @memberof EventsGetResponse200Image
     */
    trackBoxes?: Array<EventsGetResponse200ImageTrackBoxes>;
    /**
     * Содержимое изображения в формате Base64
     * @type {string}
     * @memberof EventsGetResponse200Image
     */
    content: string;
}

export function EventsGetResponse200ImageFromJSON(json: any): EventsGetResponse200Image {
    return EventsGetResponse200ImageFromJSONTyped(json, false);
}

export function EventsGetResponse200ImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsGetResponse200Image {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'compression': json['compression'],
        'width': json['width'],
        'height': json['height'],
        'trackBoxes': !exists(json, 'track_boxes') ? undefined : ((json['track_boxes'] as Array<any>).map(EventsGetResponse200ImageTrackBoxesFromJSON)),
        'content': json['content'],
    };
}

export function EventsGetResponse200ImageToJSON(value?: EventsGetResponse200Image | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'compression': value.compression,
        'width': value.width,
        'height': value.height,
        'track_boxes': value.trackBoxes === undefined ? undefined : ((value.trackBoxes as Array<any>).map(EventsGetResponse200ImageTrackBoxesToJSON)),
        'content': value.content,
    };
}


