/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.18.dev138
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Разметка обнаруженного объекта
 * @export
 * @interface EventsGetResponse200ImageTrackBox
 */
export interface EventsGetResponse200ImageTrackBox {
    /**
     * Координа по оси X левого верхнего угла
     * @type {number}
     * @memberof EventsGetResponse200ImageTrackBox
     */
    topX: number;
    /**
     * Координа по оси Y левого верхнего угла
     * @type {number}
     * @memberof EventsGetResponse200ImageTrackBox
     */
    topY: number;
    /**
     * Координа по оси X правого нижнего угла
     * @type {number}
     * @memberof EventsGetResponse200ImageTrackBox
     */
    bottomX: number;
    /**
     * Координа по оси Y правого нижнего угла
     * @type {number}
     * @memberof EventsGetResponse200ImageTrackBox
     */
    bottomY: number;
}

export function EventsGetResponse200ImageTrackBoxFromJSON(json: any): EventsGetResponse200ImageTrackBox {
    return EventsGetResponse200ImageTrackBoxFromJSONTyped(json, false);
}

export function EventsGetResponse200ImageTrackBoxFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsGetResponse200ImageTrackBox {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topX': json['top_x'],
        'topY': json['top_y'],
        'bottomX': json['bottom_x'],
        'bottomY': json['bottom_y'],
    };
}

export function EventsGetResponse200ImageTrackBoxToJSON(value?: EventsGetResponse200ImageTrackBox | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'top_x': value.topX,
        'top_y': value.topY,
        'bottom_x': value.bottomX,
        'bottom_y': value.bottomY,
    };
}


