/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev148
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Статус события
 * @export
 * @interface EventsGetResponse200Status
 */
export interface EventsGetResponse200Status {
    /**
     * Идентификатор текущего статуса
     * @type {number}
     * @memberof EventsGetResponse200Status
     */
    currentId?: number;
    /**
     * Перечень идентификаторов следующих статусов
     * @type {Array<number>}
     * @memberof EventsGetResponse200Status
     */
    nextIds: Array<number>;
}

export function EventsGetResponse200StatusFromJSON(json: any): EventsGetResponse200Status {
    return EventsGetResponse200StatusFromJSONTyped(json, false);
}

export function EventsGetResponse200StatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsGetResponse200Status {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentId': !exists(json, 'current_id') ? undefined : json['current_id'],
        'nextIds': json['next_ids'],
    };
}

export function EventsGetResponse200StatusToJSON(value?: EventsGetResponse200Status | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'current_id': value.currentId,
        'next_ids': value.nextIds,
    };
}


