/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev155
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Разметка обнаруженного объекта
 * @export
 * @interface EventsGetResponse200ImageTrackBoxes
 */
export interface EventsGetResponse200ImageTrackBoxes {
    /**
     * Координата по оси X левого верхнего угла
     * @type {number}
     * @memberof EventsGetResponse200ImageTrackBoxes
     */
    topX: number;
    /**
     * Координата по оси Y левого верхнего угла
     * @type {number}
     * @memberof EventsGetResponse200ImageTrackBoxes
     */
    topY: number;
    /**
     * Координата по оси X правого нижнего угла
     * @type {number}
     * @memberof EventsGetResponse200ImageTrackBoxes
     */
    bottomX: number;
    /**
     * Координата по оси Y правого нижнего угла
     * @type {number}
     * @memberof EventsGetResponse200ImageTrackBoxes
     */
    bottomY: number;
}

export function EventsGetResponse200ImageTrackBoxesFromJSON(json: any): EventsGetResponse200ImageTrackBoxes {
    return EventsGetResponse200ImageTrackBoxesFromJSONTyped(json, false);
}

export function EventsGetResponse200ImageTrackBoxesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsGetResponse200ImageTrackBoxes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topX': json['top_x'],
        'topY': json['top_y'],
        'bottomX': json['bottom_x'],
        'bottomY': json['bottom_y'],
    };
}

export function EventsGetResponse200ImageTrackBoxesToJSON(value?: EventsGetResponse200ImageTrackBoxes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'top_x': value.topX,
        'top_y': value.topY,
        'bottom_x': value.bottomX,
        'bottom_y': value.bottomY,
    };
}


