/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev163
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EventGetResponse200EventTrackedObject,
    EventGetResponse200EventTrackedObjectFromJSON,
    EventGetResponse200EventTrackedObjectFromJSONTyped,
    EventGetResponse200EventTrackedObjectToJSON,
    IncidentGetResponse200IncidentImage,
    IncidentGetResponse200IncidentImageFromJSON,
    IncidentGetResponse200IncidentImageFromJSONTyped,
    IncidentGetResponse200IncidentImageToJSON,
    IncidentGetResponse200IncidentStatus,
    IncidentGetResponse200IncidentStatusFromJSON,
    IncidentGetResponse200IncidentStatusFromJSONTyped,
    IncidentGetResponse200IncidentStatusToJSON,
    TimelineGetOccurrence200Thumbnail,
    TimelineGetOccurrence200ThumbnailFromJSON,
    TimelineGetOccurrence200ThumbnailFromJSONTyped,
    TimelineGetOccurrence200ThumbnailToJSON,
} from './';

/**
 * Сведения о событии
 * @export
 * @interface EventGetResponse200Event
 */
export interface EventGetResponse200Event {
    /**
     * Идентификатор проверки
     * @type {number}
     * @memberof EventGetResponse200Event
     */
    checkId: number;
    /**
     * Код события
     * @type {string}
     * @memberof EventGetResponse200Event
     */
    eventCode: string;
    /**
     * Идентификатор события
     * @type {number}
     * @memberof EventGetResponse200Event
     */
    eventId: number;
    /**
     * Дата и время совершения события в формате "YYYY-MM-DD HH:MI:SS"
     * @type {string}
     * @memberof EventGetResponse200Event
     */
    eventTimestamp: string;
    /**
     * Идентификатор площадки
     * @type {number}
     * @memberof EventGetResponse200Event
     */
    locationId: number;
    /**
     * Идентификатор датчика
     * @type {number}
     * @memberof EventGetResponse200Event
     */
    sensorId: number;
    /**
     * 
     * @type {IncidentGetResponse200IncidentStatus}
     * @memberof EventGetResponse200Event
     */
    status?: IncidentGetResponse200IncidentStatus;
    /**
     * Идентификатор категории обнаруженного объекта
     * @type {number}
     * @memberof EventGetResponse200Event
     */
    tocId: number;
    /**
     * 
     * @type {EventGetResponse200EventTrackedObject}
     * @memberof EventGetResponse200Event
     */
    trackedObject: EventGetResponse200EventTrackedObject;
    /**
     * 
     * @type {IncidentGetResponse200IncidentImage}
     * @memberof EventGetResponse200Event
     */
    image?: IncidentGetResponse200IncidentImage;
    /**
     * 
     * @type {TimelineGetOccurrence200Thumbnail}
     * @memberof EventGetResponse200Event
     */
    thumbnail?: TimelineGetOccurrence200Thumbnail;
}

export function EventGetResponse200EventFromJSON(json: any): EventGetResponse200Event {
    return EventGetResponse200EventFromJSONTyped(json, false);
}

export function EventGetResponse200EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventGetResponse200Event {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkId': json['check_id'],
        'eventCode': json['event_code'],
        'eventId': json['event_id'],
        'eventTimestamp': json['event_timestamp'],
        'locationId': json['location_id'],
        'sensorId': json['sensor_id'],
        'status': !exists(json, 'status') ? undefined : IncidentGetResponse200IncidentStatusFromJSON(json['status']),
        'tocId': json['toc_id'],
        'trackedObject': EventGetResponse200EventTrackedObjectFromJSON(json['tracked_object']),
        'image': !exists(json, 'image') ? undefined : IncidentGetResponse200IncidentImageFromJSON(json['image']),
        'thumbnail': !exists(json, 'thumbnail') ? undefined : TimelineGetOccurrence200ThumbnailFromJSON(json['thumbnail']),
    };
}

export function EventGetResponse200EventToJSON(value?: EventGetResponse200Event | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'check_id': value.checkId,
        'event_code': value.eventCode,
        'event_id': value.eventId,
        'event_timestamp': value.eventTimestamp,
        'location_id': value.locationId,
        'sensor_id': value.sensorId,
        'status': IncidentGetResponse200IncidentStatusToJSON(value.status),
        'toc_id': value.tocId,
        'tracked_object': EventGetResponse200EventTrackedObjectToJSON(value.trackedObject),
        'image': IncidentGetResponse200IncidentImageToJSON(value.image),
        'thumbnail': TimelineGetOccurrence200ThumbnailToJSON(value.thumbnail),
    };
}


