/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev155
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EventsGetResponse200TrackedObjectExtra,
    EventsGetResponse200TrackedObjectExtraFromJSON,
    EventsGetResponse200TrackedObjectExtraFromJSONTyped,
    EventsGetResponse200TrackedObjectExtraToJSON,
} from './';

/**
 * Сведения об обнаруженном объекте
 * @export
 * @interface EventsGetResponse200TrackedObject
 */
export interface EventsGetResponse200TrackedObject {
    /**
     * Идентификатор транспортного средства
     * @type {number}
     * @memberof EventsGetResponse200TrackedObject
     */
    id: number;
    /**
     * Код транспортного средства
     * @type {string}
     * @memberof EventsGetResponse200TrackedObject
     */
    code: string;
    /**
     * Перечень дополнительных атрибутов по обнаруженному объекту
     * @type {Array<EventsGetResponse200TrackedObjectExtra>}
     * @memberof EventsGetResponse200TrackedObject
     */
    extra: Array<EventsGetResponse200TrackedObjectExtra>;
}

export function EventsGetResponse200TrackedObjectFromJSON(json: any): EventsGetResponse200TrackedObject {
    return EventsGetResponse200TrackedObjectFromJSONTyped(json, false);
}

export function EventsGetResponse200TrackedObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsGetResponse200TrackedObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'extra': ((json['extra'] as Array<any>).map(EventsGetResponse200TrackedObjectExtraFromJSON)),
    };
}

export function EventsGetResponse200TrackedObjectToJSON(value?: EventsGetResponse200TrackedObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'extra': ((value.extra as Array<any>).map(EventsGetResponse200TrackedObjectExtraToJSON)),
    };
}


