/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev156
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IncidentGetResponse200Incident,
    IncidentGetResponse200IncidentFromJSON,
    IncidentGetResponse200IncidentFromJSONTyped,
    IncidentGetResponse200IncidentToJSON,
} from './';

/**
 * 
 * @export
 * @interface IncidentGetResponse200
 */
export interface IncidentGetResponse200 {
    /**
     * 
     * @type {IncidentGetResponse200Incident}
     * @memberof IncidentGetResponse200
     */
    incident?: IncidentGetResponse200Incident;
}

export function IncidentGetResponse200FromJSON(json: any): IncidentGetResponse200 {
    return IncidentGetResponse200FromJSONTyped(json, false);
}

export function IncidentGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'incident': !exists(json, 'incident') ? undefined : IncidentGetResponse200IncidentFromJSON(json['incident']),
    };
}

export function IncidentGetResponse200ToJSON(value?: IncidentGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'incident': IncidentGetResponse200IncidentToJSON(value.incident),
    };
}


