/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev161
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IncidentGetResponse200IncidentTrackedObjectExtra,
    IncidentGetResponse200IncidentTrackedObjectExtraFromJSON,
    IncidentGetResponse200IncidentTrackedObjectExtraFromJSONTyped,
    IncidentGetResponse200IncidentTrackedObjectExtraToJSON,
} from './';

/**
 * Сведения об обнаруженном объекте
 * @export
 * @interface IncidentGetResponse200IncidentTrackedObject
 */
export interface IncidentGetResponse200IncidentTrackedObject {
    /**
     * Идентификатор транспортного средства
     * @type {number}
     * @memberof IncidentGetResponse200IncidentTrackedObject
     */
    id: number;
    /**
     * Код транспортного средства
     * @type {string}
     * @memberof IncidentGetResponse200IncidentTrackedObject
     */
    code: string;
    /**
     * Перечень дополнительных атрибутов по обнаруженному объекту
     * @type {Array<IncidentGetResponse200IncidentTrackedObjectExtra>}
     * @memberof IncidentGetResponse200IncidentTrackedObject
     */
    extra: Array<IncidentGetResponse200IncidentTrackedObjectExtra>;
}

export function IncidentGetResponse200IncidentTrackedObjectFromJSON(json: any): IncidentGetResponse200IncidentTrackedObject {
    return IncidentGetResponse200IncidentTrackedObjectFromJSONTyped(json, false);
}

export function IncidentGetResponse200IncidentTrackedObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentGetResponse200IncidentTrackedObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'extra': ((json['extra'] as Array<any>).map(IncidentGetResponse200IncidentTrackedObjectExtraFromJSON)),
    };
}

export function IncidentGetResponse200IncidentTrackedObjectToJSON(value?: IncidentGetResponse200IncidentTrackedObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'extra': ((value.extra as Array<any>).map(IncidentGetResponse200IncidentTrackedObjectExtraToJSON)),
    };
}


