/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev156
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IncidentGetResponse200Incident,
    IncidentGetResponse200IncidentFromJSON,
    IncidentGetResponse200IncidentFromJSONTyped,
    IncidentGetResponse200IncidentToJSON,
    IncidentsGetResponse200Pagination,
    IncidentsGetResponse200PaginationFromJSON,
    IncidentsGetResponse200PaginationFromJSONTyped,
    IncidentsGetResponse200PaginationToJSON,
    IncidentsGetResponse200Period,
    IncidentsGetResponse200PeriodFromJSON,
    IncidentsGetResponse200PeriodFromJSONTyped,
    IncidentsGetResponse200PeriodToJSON,
} from './';

/**
 * 
 * @export
 * @interface IncidentsGetResponse200
 */
export interface IncidentsGetResponse200 {
    /**
     * 
     * @type {IncidentsGetResponse200Pagination}
     * @memberof IncidentsGetResponse200
     */
    pagination: IncidentsGetResponse200Pagination;
    /**
     * 
     * @type {IncidentsGetResponse200Period}
     * @memberof IncidentsGetResponse200
     */
    period: IncidentsGetResponse200Period;
    /**
     * Перечень инцидентов
     * @type {Array<IncidentGetResponse200Incident>}
     * @memberof IncidentsGetResponse200
     */
    incidents: Array<IncidentGetResponse200Incident>;
}

export function IncidentsGetResponse200FromJSON(json: any): IncidentsGetResponse200 {
    return IncidentsGetResponse200FromJSONTyped(json, false);
}

export function IncidentsGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentsGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': IncidentsGetResponse200PaginationFromJSON(json['pagination']),
        'period': IncidentsGetResponse200PeriodFromJSON(json['period']),
        'incidents': ((json['incidents'] as Array<any>).map(IncidentGetResponse200IncidentFromJSON)),
    };
}

export function IncidentsGetResponse200ToJSON(value?: IncidentsGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pagination': IncidentsGetResponse200PaginationToJSON(value.pagination),
        'period': IncidentsGetResponse200PeriodToJSON(value.period),
        'incidents': ((value.incidents as Array<any>).map(IncidentGetResponse200IncidentToJSON)),
    };
}


