/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.17.dev126
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IncidentsGetResponse200Status,
    IncidentsGetResponse200StatusFromJSON,
    IncidentsGetResponse200StatusFromJSONTyped,
    IncidentsGetResponse200StatusToJSON,
    IncidentsGetResponse200TrackedObject,
    IncidentsGetResponse200TrackedObjectFromJSON,
    IncidentsGetResponse200TrackedObjectFromJSONTyped,
    IncidentsGetResponse200TrackedObjectToJSON,
} from './';

/**
 * Сведения о событии
 * @export
 * @interface IncidentsGetResponse200Incidents
 */
export interface IncidentsGetResponse200Incidents {
    /**
     * Идентификатор проверки
     * @type {number}
     * @memberof IncidentsGetResponse200Incidents
     */
    checkId: number;
    /**
     * Код события
     * @type {string}
     * @memberof IncidentsGetResponse200Incidents
     */
    eventCode: string;
    /**
     * Дата и время совершения события в формате "YYYY-MM-DD HH:MI:SS"
     * @type {string}
     * @memberof IncidentsGetResponse200Incidents
     */
    eventTimestamp: string;
    /**
     * Идентификатор инцидента
     * @type {number}
     * @memberof IncidentsGetResponse200Incidents
     */
    id: number;
    /**
     * Идентификатор категории инцидента
     * @type {number}
     * @memberof IncidentsGetResponse200Incidents
     */
    incidentId: number;
    /**
     * Идентификатор площадки
     * @type {number}
     * @memberof IncidentsGetResponse200Incidents
     */
    locationId: number;
    /**
     * Идентификатор датчика
     * @type {number}
     * @memberof IncidentsGetResponse200Incidents
     */
    sensorId: number;
    /**
     * 
     * @type {IncidentsGetResponse200Status}
     * @memberof IncidentsGetResponse200Incidents
     */
    status?: IncidentsGetResponse200Status;
    /**
     * Идентификатор категории обнаруженного объекта
     * @type {number}
     * @memberof IncidentsGetResponse200Incidents
     */
    tocId: number;
    /**
     * 
     * @type {IncidentsGetResponse200TrackedObject}
     * @memberof IncidentsGetResponse200Incidents
     */
    trackedObject: IncidentsGetResponse200TrackedObject;
}

export function IncidentsGetResponse200IncidentsFromJSON(json: any): IncidentsGetResponse200Incidents {
    return IncidentsGetResponse200IncidentsFromJSONTyped(json, false);
}

export function IncidentsGetResponse200IncidentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentsGetResponse200Incidents {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkId': json['check_id'],
        'eventCode': json['event_code'],
        'eventTimestamp': json['event_timestamp'],
        'id': json['id'],
        'incidentId': json['incident_id'],
        'locationId': json['location_id'],
        'sensorId': json['sensor_id'],
        'status': !exists(json, 'status') ? undefined : IncidentsGetResponse200StatusFromJSON(json['status']),
        'tocId': json['toc_id'],
        'trackedObject': IncidentsGetResponse200TrackedObjectFromJSON(json['tracked_object']),
    };
}

export function IncidentsGetResponse200IncidentsToJSON(value?: IncidentsGetResponse200Incidents | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'check_id': value.checkId,
        'event_code': value.eventCode,
        'event_timestamp': value.eventTimestamp,
        'id': value.id,
        'incident_id': value.incidentId,
        'location_id': value.locationId,
        'sensor_id': value.sensorId,
        'status': IncidentsGetResponse200StatusToJSON(value.status),
        'toc_id': value.tocId,
        'tracked_object': IncidentsGetResponse200TrackedObjectToJSON(value.trackedObject),
    };
}


