/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev153
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IncidentGetResponse200IncidentPeriodStart,
    IncidentGetResponse200IncidentPeriodStartFromJSON,
    IncidentGetResponse200IncidentPeriodStartFromJSONTyped,
    IncidentGetResponse200IncidentPeriodStartToJSON,
} from './';

/**
 * null
 * @export
 * @interface IncidentGetResponse200IncidentPeriod
 */
export interface IncidentGetResponse200IncidentPeriod {
    /**
     * 
     * @type {IncidentGetResponse200IncidentPeriodStart}
     * @memberof IncidentGetResponse200IncidentPeriod
     */
    start: IncidentGetResponse200IncidentPeriodStart;
    /**
     * 
     * @type {object}
     * @memberof IncidentGetResponse200IncidentPeriod
     */
    end: object;
}

export function IncidentGetResponse200IncidentPeriodFromJSON(json: any): IncidentGetResponse200IncidentPeriod {
    return IncidentGetResponse200IncidentPeriodFromJSONTyped(json, false);
}

export function IncidentGetResponse200IncidentPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentGetResponse200IncidentPeriod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': IncidentGetResponse200IncidentPeriodStartFromJSON(json['start']),
        'end': json['end'],
    };
}

export function IncidentGetResponse200IncidentPeriodToJSON(value?: IncidentGetResponse200IncidentPeriod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': IncidentGetResponse200IncidentPeriodStartToJSON(value.start),
        'end': value.end,
    };
}


