/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.16.dev115
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IncidentsGetResponse200Incidents,
    IncidentsGetResponse200IncidentsFromJSON,
    IncidentsGetResponse200IncidentsFromJSONTyped,
    IncidentsGetResponse200IncidentsToJSON,
    IncidentsGetResponse200Period,
    IncidentsGetResponse200PeriodFromJSON,
    IncidentsGetResponse200PeriodFromJSONTyped,
    IncidentsGetResponse200PeriodToJSON,
} from './';

/**
 * 
 * @export
 * @interface IncidentsGetResponse200
 */
export interface IncidentsGetResponse200 {
    /**
     * 
     * @type {IncidentsGetResponse200Period}
     * @memberof IncidentsGetResponse200
     */
    period: IncidentsGetResponse200Period;
    /**
     * Перечень инцидентов
     * @type {Array<IncidentsGetResponse200Incidents>}
     * @memberof IncidentsGetResponse200
     */
    incidents: Array<IncidentsGetResponse200Incidents>;
}

export function IncidentsGetResponse200FromJSON(json: any): IncidentsGetResponse200 {
    return IncidentsGetResponse200FromJSONTyped(json, false);
}

export function IncidentsGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentsGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'period': IncidentsGetResponse200PeriodFromJSON(json['period']),
        'incidents': ((json['incidents'] as Array<any>).map(IncidentsGetResponse200IncidentsFromJSON)),
    };
}

export function IncidentsGetResponse200ToJSON(value?: IncidentsGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'period': IncidentsGetResponse200PeriodToJSON(value.period),
        'incidents': ((value.incidents as Array<any>).map(IncidentsGetResponse200IncidentsToJSON)),
    };
}


