/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev162
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Разметка обнаруженного объекта
 * @export
 * @interface IncidentGetResponse200IncidentImageTrackBoxes
 */
export interface IncidentGetResponse200IncidentImageTrackBoxes {
    /**
     * Координата по оси X левого верхнего угла
     * @type {number}
     * @memberof IncidentGetResponse200IncidentImageTrackBoxes
     */
    topX: number;
    /**
     * Координата по оси Y левого верхнего угла
     * @type {number}
     * @memberof IncidentGetResponse200IncidentImageTrackBoxes
     */
    topY: number;
    /**
     * Координата по оси X правого нижнего угла
     * @type {number}
     * @memberof IncidentGetResponse200IncidentImageTrackBoxes
     */
    bottomX: number;
    /**
     * Координата по оси Y правого нижнего угла
     * @type {number}
     * @memberof IncidentGetResponse200IncidentImageTrackBoxes
     */
    bottomY: number;
}

export function IncidentGetResponse200IncidentImageTrackBoxesFromJSON(json: any): IncidentGetResponse200IncidentImageTrackBoxes {
    return IncidentGetResponse200IncidentImageTrackBoxesFromJSONTyped(json, false);
}

export function IncidentGetResponse200IncidentImageTrackBoxesFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentGetResponse200IncidentImageTrackBoxes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topX': json['top_x'],
        'topY': json['top_y'],
        'bottomX': json['bottom_x'],
        'bottomY': json['bottom_y'],
    };
}

export function IncidentGetResponse200IncidentImageTrackBoxesToJSON(value?: IncidentGetResponse200IncidentImageTrackBoxes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'top_x': value.topX,
        'top_y': value.topY,
        'bottom_x': value.bottomX,
        'bottom_y': value.bottomY,
    };
}


