/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev153
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EventsGetResponse200Image,
    EventsGetResponse200ImageFromJSON,
    EventsGetResponse200ImageFromJSONTyped,
    EventsGetResponse200ImageToJSON,
    EventsGetResponse200Status,
    EventsGetResponse200StatusFromJSON,
    EventsGetResponse200StatusFromJSONTyped,
    EventsGetResponse200StatusToJSON,
    EventsGetResponse200TrackedObject,
    EventsGetResponse200TrackedObjectFromJSON,
    EventsGetResponse200TrackedObjectFromJSONTyped,
    EventsGetResponse200TrackedObjectToJSON,
    IncidentGetResponse200IncidentPeriod,
    IncidentGetResponse200IncidentPeriodFromJSON,
    IncidentGetResponse200IncidentPeriodFromJSONTyped,
    IncidentGetResponse200IncidentPeriodToJSON,
    IncidentGetResponse200IncidentThumbnail,
    IncidentGetResponse200IncidentThumbnailFromJSON,
    IncidentGetResponse200IncidentThumbnailFromJSONTyped,
    IncidentGetResponse200IncidentThumbnailToJSON,
} from './';

/**
 * Сведения об инциденте
 * @export
 * @interface IncidentGetResponse200Incident
 */
export interface IncidentGetResponse200Incident {
    /**
     * Идентификатор категории инцидента
     * @type {number}
     * @memberof IncidentGetResponse200Incident
     */
    categoryId: number;
    /**
     * Идентификатор инцидента
     * @type {number}
     * @memberof IncidentGetResponse200Incident
     */
    id: number;
    /**
     * Список идентификаторов событий по инциденту
     * @type {Array<number>}
     * @memberof IncidentGetResponse200Incident
     */
    eventIds: Array<number>;
    /**
     * 
     * @type {EventsGetResponse200Image}
     * @memberof IncidentGetResponse200Incident
     */
    image: EventsGetResponse200Image;
    /**
     * Идентификатор площадки
     * @type {number}
     * @memberof IncidentGetResponse200Incident
     */
    locationId: number;
    /**
     * 
     * @type {IncidentGetResponse200IncidentPeriod}
     * @memberof IncidentGetResponse200Incident
     */
    period: IncidentGetResponse200IncidentPeriod;
    /**
     * Идентификатор датчика
     * @type {number}
     * @memberof IncidentGetResponse200Incident
     */
    sensorId: number;
    /**
     * 
     * @type {EventsGetResponse200Status}
     * @memberof IncidentGetResponse200Incident
     */
    status: EventsGetResponse200Status;
    /**
     * 
     * @type {IncidentGetResponse200IncidentThumbnail}
     * @memberof IncidentGetResponse200Incident
     */
    thumbnail: IncidentGetResponse200IncidentThumbnail;
    /**
     * Идентификатор категории обнаруженного объекта
     * @type {number}
     * @memberof IncidentGetResponse200Incident
     */
    tocId: number;
    /**
     * 
     * @type {EventsGetResponse200TrackedObject}
     * @memberof IncidentGetResponse200Incident
     */
    trackedObject: EventsGetResponse200TrackedObject;
}

export function IncidentGetResponse200IncidentFromJSON(json: any): IncidentGetResponse200Incident {
    return IncidentGetResponse200IncidentFromJSONTyped(json, false);
}

export function IncidentGetResponse200IncidentFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentGetResponse200Incident {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categoryId': json['category_id'],
        'id': json['id'],
        'eventIds': json['event_ids'],
        'image': EventsGetResponse200ImageFromJSON(json['image']),
        'locationId': json['location_id'],
        'period': IncidentGetResponse200IncidentPeriodFromJSON(json['period']),
        'sensorId': json['sensor_id'],
        'status': EventsGetResponse200StatusFromJSON(json['status']),
        'thumbnail': IncidentGetResponse200IncidentThumbnailFromJSON(json['thumbnail']),
        'tocId': json['toc_id'],
        'trackedObject': EventsGetResponse200TrackedObjectFromJSON(json['tracked_object']),
    };
}

export function IncidentGetResponse200IncidentToJSON(value?: IncidentGetResponse200Incident | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'category_id': value.categoryId,
        'id': value.id,
        'event_ids': value.eventIds,
        'image': EventsGetResponse200ImageToJSON(value.image),
        'location_id': value.locationId,
        'period': IncidentGetResponse200IncidentPeriodToJSON(value.period),
        'sensor_id': value.sensorId,
        'status': EventsGetResponse200StatusToJSON(value.status),
        'thumbnail': IncidentGetResponse200IncidentThumbnailToJSON(value.thumbnail),
        'toc_id': value.tocId,
        'tracked_object': EventsGetResponse200TrackedObjectToJSON(value.trackedObject),
    };
}


