/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.14.dev96
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * null
 * @export
 * @interface InoutLatestEventsGetResponse200TrackedObject
 */
export interface InoutLatestEventsGetResponse200TrackedObject {
    /**
     * Код отслеживаемого объекта
     * @type {string}
     * @memberof InoutLatestEventsGetResponse200TrackedObject
     */
    code: string;
    /**
     * Государственный регистрационный номер транспортного средства
     * @type {string}
     * @memberof InoutLatestEventsGetResponse200TrackedObject
     */
    licensePlateNumber: string;
}

export function InoutLatestEventsGetResponse200TrackedObjectFromJSON(json: any): InoutLatestEventsGetResponse200TrackedObject {
    return InoutLatestEventsGetResponse200TrackedObjectFromJSONTyped(json, false);
}

export function InoutLatestEventsGetResponse200TrackedObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InoutLatestEventsGetResponse200TrackedObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'licensePlateNumber': json['license_plate_number'],
    };
}

export function InoutLatestEventsGetResponse200TrackedObjectToJSON(value?: InoutLatestEventsGetResponse200TrackedObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'license_plate_number': value.licensePlateNumber,
    };
}


