/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.14.dev96
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InoutLatestEventsGetResponse200Events,
    InoutLatestEventsGetResponse200EventsFromJSON,
    InoutLatestEventsGetResponse200EventsFromJSONTyped,
    InoutLatestEventsGetResponse200EventsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InoutLatestEventsGetResponse200
 */
export interface InoutLatestEventsGetResponse200 {
    /**
     * 
     * @type {Array<InoutLatestEventsGetResponse200Events>}
     * @memberof InoutLatestEventsGetResponse200
     */
    events: Array<InoutLatestEventsGetResponse200Events>;
}

export function InoutLatestEventsGetResponse200FromJSON(json: any): InoutLatestEventsGetResponse200 {
    return InoutLatestEventsGetResponse200FromJSONTyped(json, false);
}

export function InoutLatestEventsGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): InoutLatestEventsGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(InoutLatestEventsGetResponse200EventsFromJSON)),
    };
}

export function InoutLatestEventsGetResponse200ToJSON(value?: InoutLatestEventsGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'events': ((value.events as Array<any>).map(InoutLatestEventsGetResponse200EventsToJSON)),
    };
}


