/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.17.dev126
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Сведения о площадке
 * @export
 * @interface InoutEventsStatsGetResponse200Location
 */
export interface InoutEventsStatsGetResponse200Location {
    /**
     * Идентификатор площадки
     * @type {number}
     * @memberof InoutEventsStatsGetResponse200Location
     */
    id: number;
}

export function InoutEventsStatsGetResponse200LocationFromJSON(json: any): InoutEventsStatsGetResponse200Location {
    return InoutEventsStatsGetResponse200LocationFromJSONTyped(json, false);
}

export function InoutEventsStatsGetResponse200LocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): InoutEventsStatsGetResponse200Location {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function InoutEventsStatsGetResponse200LocationToJSON(value?: InoutEventsStatsGetResponse200Location | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


