/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.15.dev108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InoutEventsStatsGetResponse200Location,
    InoutEventsStatsGetResponse200LocationFromJSON,
    InoutEventsStatsGetResponse200LocationFromJSONTyped,
    InoutEventsStatsGetResponse200LocationToJSON,
    InoutEventsStatsGetResponse200Sensor,
    InoutEventsStatsGetResponse200SensorFromJSON,
    InoutEventsStatsGetResponse200SensorFromJSONTyped,
    InoutEventsStatsGetResponse200SensorToJSON,
    InoutEventsStatsGetResponse200Today,
    InoutEventsStatsGetResponse200TodayFromJSON,
    InoutEventsStatsGetResponse200TodayFromJSONTyped,
    InoutEventsStatsGetResponse200TodayToJSON,
    InoutEventsStatsGetResponse200TrackedObjectCategory,
    InoutEventsStatsGetResponse200TrackedObjectCategoryFromJSON,
    InoutEventsStatsGetResponse200TrackedObjectCategoryFromJSONTyped,
    InoutEventsStatsGetResponse200TrackedObjectCategoryToJSON,
} from './';

/**
 * Статистика за текущий день
 * @export
 * @interface InoutEventsStatsGetResponse200Stats
 */
export interface InoutEventsStatsGetResponse200Stats {
    /**
     * 
     * @type {InoutEventsStatsGetResponse200Location}
     * @memberof InoutEventsStatsGetResponse200Stats
     */
    location: InoutEventsStatsGetResponse200Location;
    /**
     * 
     * @type {InoutEventsStatsGetResponse200Sensor}
     * @memberof InoutEventsStatsGetResponse200Stats
     */
    sensor: InoutEventsStatsGetResponse200Sensor;
    /**
     * 
     * @type {InoutEventsStatsGetResponse200TrackedObjectCategory}
     * @memberof InoutEventsStatsGetResponse200Stats
     */
    trackedObjectCategory: InoutEventsStatsGetResponse200TrackedObjectCategory;
    /**
     * 
     * @type {InoutEventsStatsGetResponse200Today}
     * @memberof InoutEventsStatsGetResponse200Stats
     */
    today: InoutEventsStatsGetResponse200Today;
}

export function InoutEventsStatsGetResponse200StatsFromJSON(json: any): InoutEventsStatsGetResponse200Stats {
    return InoutEventsStatsGetResponse200StatsFromJSONTyped(json, false);
}

export function InoutEventsStatsGetResponse200StatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InoutEventsStatsGetResponse200Stats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'location': InoutEventsStatsGetResponse200LocationFromJSON(json['location']),
        'sensor': InoutEventsStatsGetResponse200SensorFromJSON(json['sensor']),
        'trackedObjectCategory': InoutEventsStatsGetResponse200TrackedObjectCategoryFromJSON(json['tracked_object_category']),
        'today': InoutEventsStatsGetResponse200TodayFromJSON(json['today']),
    };
}

export function InoutEventsStatsGetResponse200StatsToJSON(value?: InoutEventsStatsGetResponse200Stats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'location': InoutEventsStatsGetResponse200LocationToJSON(value.location),
        'sensor': InoutEventsStatsGetResponse200SensorToJSON(value.sensor),
        'tracked_object_category': InoutEventsStatsGetResponse200TrackedObjectCategoryToJSON(value.trackedObjectCategory),
        'today': InoutEventsStatsGetResponse200TodayToJSON(value.today),
    };
}


