/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Сведения о датчике
 * @export
 * @interface InoutLatestEventsGetResponse200Sensor
 */
export interface InoutLatestEventsGetResponse200Sensor {
    /**
     * Идентификатор датчика
     * @type {number}
     * @memberof InoutLatestEventsGetResponse200Sensor
     */
    id: number;
}

export function InoutLatestEventsGetResponse200SensorFromJSON(json: any): InoutLatestEventsGetResponse200Sensor {
    return InoutLatestEventsGetResponse200SensorFromJSONTyped(json, false);
}

export function InoutLatestEventsGetResponse200SensorFromJSONTyped(json: any, ignoreDiscriminator: boolean): InoutLatestEventsGetResponse200Sensor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function InoutLatestEventsGetResponse200SensorToJSON(value?: InoutLatestEventsGetResponse200Sensor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


