/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.14.dev96
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Сведения о категории отслеживаемых объектов
 * @export
 * @interface InoutLatestEventsGetResponse200TrackedObjectCategory
 */
export interface InoutLatestEventsGetResponse200TrackedObjectCategory {
    /**
     * Идентификатор категории отслеживаемых объектов
     * @type {number}
     * @memberof InoutLatestEventsGetResponse200TrackedObjectCategory
     */
    id: number;
}

export function InoutLatestEventsGetResponse200TrackedObjectCategoryFromJSON(json: any): InoutLatestEventsGetResponse200TrackedObjectCategory {
    return InoutLatestEventsGetResponse200TrackedObjectCategoryFromJSONTyped(json, false);
}

export function InoutLatestEventsGetResponse200TrackedObjectCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): InoutLatestEventsGetResponse200TrackedObjectCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function InoutLatestEventsGetResponse200TrackedObjectCategoryToJSON(value?: InoutLatestEventsGetResponse200TrackedObjectCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


