/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.18.dev138
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LatestEventsGetResponse200Events,
    LatestEventsGetResponse200EventsFromJSON,
    LatestEventsGetResponse200EventsFromJSONTyped,
    LatestEventsGetResponse200EventsToJSON,
} from './';

/**
 * 
 * @export
 * @interface LatestEventsGetResponse200
 */
export interface LatestEventsGetResponse200 {
    /**
     * 
     * @type {Array<LatestEventsGetResponse200Events>}
     * @memberof LatestEventsGetResponse200
     */
    events: Array<LatestEventsGetResponse200Events>;
}

export function LatestEventsGetResponse200FromJSON(json: any): LatestEventsGetResponse200 {
    return LatestEventsGetResponse200FromJSONTyped(json, false);
}

export function LatestEventsGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): LatestEventsGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(LatestEventsGetResponse200EventsFromJSON)),
    };
}

export function LatestEventsGetResponse200ToJSON(value?: LatestEventsGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'events': ((value.events as Array<any>).map(LatestEventsGetResponse200EventsToJSON)),
    };
}


