/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev163
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Сведения о связке правило-логический конвейер компании
 * @export
 * @interface PipelineCheckGetResponse200
 */
export interface PipelineCheckGetResponse200 {
    /**
     * Идентификатор связки
     * @type {number}
     * @memberof PipelineCheckGetResponse200
     */
    id: number;
    /**
     * Идентификатор логического конвейера
     * @type {number}
     * @memberof PipelineCheckGetResponse200
     */
    pipelineId: number;
    /**
     * Идентификатор правила
     * @type {number}
     * @memberof PipelineCheckGetResponse200
     */
    checkId: number;
    /**
     * Признак активной связки
     * @type {boolean}
     * @memberof PipelineCheckGetResponse200
     */
    enabled: boolean;
}

export function PipelineCheckGetResponse200FromJSON(json: any): PipelineCheckGetResponse200 {
    return PipelineCheckGetResponse200FromJSONTyped(json, false);
}

export function PipelineCheckGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineCheckGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'pipelineId': json['pipeline_id'],
        'checkId': json['check_id'],
        'enabled': json['enabled'],
    };
}

export function PipelineCheckGetResponse200ToJSON(value?: PipelineCheckGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'pipeline_id': value.pipelineId,
        'check_id': value.checkId,
        'enabled': value.enabled,
    };
}


