/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev161
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Описание трекера
 * @export
 * @interface PipelineGetResponse200Tracker
 */
export interface PipelineGetResponse200Tracker {
    /**
     * Идентификатор трекера
     * @type {number}
     * @memberof PipelineGetResponse200Tracker
     */
    id: number;
    /**
     * Параметры трекера
     * @type {object}
     * @memberof PipelineGetResponse200Tracker
     */
    parameters: object;
}

export function PipelineGetResponse200TrackerFromJSON(json: any): PipelineGetResponse200Tracker {
    return PipelineGetResponse200TrackerFromJSONTyped(json, false);
}

export function PipelineGetResponse200TrackerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineGetResponse200Tracker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'parameters': json['parameters'],
    };
}

export function PipelineGetResponse200TrackerToJSON(value?: PipelineGetResponse200Tracker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'parameters': value.parameters,
    };
}


