/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev160
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Описание модели детектора
 * @export
 * @interface PipelineGetResponse200DetectorModel
 */
export interface PipelineGetResponse200DetectorModel {
    /**
     * Идентификатор модели
     * @type {number}
     * @memberof PipelineGetResponse200DetectorModel
     */
    id: number;
    /**
     * Параметры модели
     * @type {object}
     * @memberof PipelineGetResponse200DetectorModel
     */
    parameters: object;
}

export function PipelineGetResponse200DetectorModelFromJSON(json: any): PipelineGetResponse200DetectorModel {
    return PipelineGetResponse200DetectorModelFromJSONTyped(json, false);
}

export function PipelineGetResponse200DetectorModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineGetResponse200DetectorModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'parameters': json['parameters'],
    };
}

export function PipelineGetResponse200DetectorModelToJSON(value?: PipelineGetResponse200DetectorModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'parameters': value.parameters,
    };
}


