/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev163
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipelineCheckPatchRequest
 */
export interface PipelineCheckPatchRequest {
    /**
     * Признак активной связки правило-конвейер
     * @type {boolean}
     * @memberof PipelineCheckPatchRequest
     */
    enabled: boolean;
}

export function PipelineCheckPatchRequestFromJSON(json: any): PipelineCheckPatchRequest {
    return PipelineCheckPatchRequestFromJSONTyped(json, false);
}

export function PipelineCheckPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineCheckPatchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
    };
}

export function PipelineCheckPatchRequestToJSON(value?: PipelineCheckPatchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}


