/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.16.dev115
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Сведения о проверке
 * @export
 * @interface PipelinesGetResponse200ConfChecks
 */
export interface PipelinesGetResponse200ConfChecks {
    /**
     * Идентификатор проверки
     * @type {number}
     * @memberof PipelinesGetResponse200ConfChecks
     */
    id: number;
    /**
     * Идентификатор модели
     * @type {number}
     * @memberof PipelinesGetResponse200ConfChecks
     */
    modelId: number;
    /**
     * Порядковый номер запуска
     * @type {number}
     * @memberof PipelinesGetResponse200ConfChecks
     */
    sequence: number;
}

export function PipelinesGetResponse200ConfChecksFromJSON(json: any): PipelinesGetResponse200ConfChecks {
    return PipelinesGetResponse200ConfChecksFromJSONTyped(json, false);
}

export function PipelinesGetResponse200ConfChecksFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelinesGetResponse200ConfChecks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'modelId': json['model_id'],
        'sequence': json['sequence'],
    };
}

export function PipelinesGetResponse200ConfChecksToJSON(value?: PipelinesGetResponse200ConfChecks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'model_id': value.modelId,
        'sequence': value.sequence,
    };
}


