/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev163
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PipelineChecksGetResponse200Checks,
    PipelineChecksGetResponse200ChecksFromJSON,
    PipelineChecksGetResponse200ChecksFromJSONTyped,
    PipelineChecksGetResponse200ChecksToJSON,
} from './';

/**
 * 
 * @export
 * @interface PipelineChecksGetResponse200
 */
export interface PipelineChecksGetResponse200 {
    /**
     * 
     * @type {Array<PipelineChecksGetResponse200Checks>}
     * @memberof PipelineChecksGetResponse200
     */
    checks: Array<PipelineChecksGetResponse200Checks>;
}

export function PipelineChecksGetResponse200FromJSON(json: any): PipelineChecksGetResponse200 {
    return PipelineChecksGetResponse200FromJSONTyped(json, false);
}

export function PipelineChecksGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineChecksGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checks': ((json['checks'] as Array<any>).map(PipelineChecksGetResponse200ChecksFromJSON)),
    };
}

export function PipelineChecksGetResponse200ToJSON(value?: PipelineChecksGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checks': ((value.checks as Array<any>).map(PipelineChecksGetResponse200ChecksToJSON)),
    };
}


