/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev156
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PipelinesGetResponse200BySensor,
    PipelinesGetResponse200BySensorFromJSON,
    PipelinesGetResponse200BySensorFromJSONTyped,
    PipelinesGetResponse200BySensorToJSON,
} from './';

/**
 * Сведения о конвейере
 * @export
 * @interface PipelinesGetResponse200Pipelines
 */
export interface PipelinesGetResponse200Pipelines {
    /**
     * Идентификатор конвейера
     * @type {number}
     * @memberof PipelinesGetResponse200Pipelines
     */
    id: number;
    /**
     * Идентификатор компании
     * @type {number}
     * @memberof PipelinesGetResponse200Pipelines
     */
    companyId: number;
    /**
     * Параметры деплоя конвейера
     * @type {object}
     * @memberof PipelinesGetResponse200Pipelines
     */
    deploy: object;
    /**
     * Перечень физических конвейеров
     * @type {Array<PipelinesGetResponse200BySensor>}
     * @memberof PipelinesGetResponse200Pipelines
     */
    bySensor: Array<PipelinesGetResponse200BySensor>;
}

export function PipelinesGetResponse200PipelinesFromJSON(json: any): PipelinesGetResponse200Pipelines {
    return PipelinesGetResponse200PipelinesFromJSONTyped(json, false);
}

export function PipelinesGetResponse200PipelinesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelinesGetResponse200Pipelines {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'companyId': json['company_id'],
        'deploy': json['deploy'],
        'bySensor': ((json['by_sensor'] as Array<any>).map(PipelinesGetResponse200BySensorFromJSON)),
    };
}

export function PipelinesGetResponse200PipelinesToJSON(value?: PipelinesGetResponse200Pipelines | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'company_id': value.companyId,
        'deploy': value.deploy,
        'by_sensor': ((value.bySensor as Array<any>).map(PipelinesGetResponse200BySensorToJSON)),
    };
}


