/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev162
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Сведения о правиле физического конвейера компании
 * @export
 * @interface PipelineSensorCheckPatchRequest
 */
export interface PipelineSensorCheckPatchRequest {
    /**
     * Признак активного правила
     * @type {boolean}
     * @memberof PipelineSensorCheckPatchRequest
     */
    enabled?: boolean;
    /**
     * Дополнительные параметры правила в JSON-формате
     * @type {object}
     * @memberof PipelineSensorCheckPatchRequest
     */
    extra?: object;
}

export function PipelineSensorCheckPatchRequestFromJSON(json: any): PipelineSensorCheckPatchRequest {
    return PipelineSensorCheckPatchRequestFromJSONTyped(json, false);
}

export function PipelineSensorCheckPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineSensorCheckPatchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'extra': !exists(json, 'extra') ? undefined : json['extra'],
    };
}

export function PipelineSensorCheckPatchRequestToJSON(value?: PipelineSensorCheckPatchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'extra': value.extra,
    };
}


