/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev163
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Разметка камеры
 * @export
 * @interface PipelineSensorCheckPatchRequestMarkup
 */
export interface PipelineSensorCheckPatchRequestMarkup {
    /**
     * Массив полигонов
     * @type {Array<Array<object>>}
     * @memberof PipelineSensorCheckPatchRequestMarkup
     */
    polygons: Array<Array<object>>;
}

export function PipelineSensorCheckPatchRequestMarkupFromJSON(json: any): PipelineSensorCheckPatchRequestMarkup {
    return PipelineSensorCheckPatchRequestMarkupFromJSONTyped(json, false);
}

export function PipelineSensorCheckPatchRequestMarkupFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineSensorCheckPatchRequestMarkup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'polygons': json['polygons'],
    };
}

export function PipelineSensorCheckPatchRequestMarkupToJSON(value?: PipelineSensorCheckPatchRequestMarkup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'polygons': value.polygons,
    };
}


