/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.16.dev115
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RefIncidentsGetResponse200Incidents,
    RefIncidentsGetResponse200IncidentsFromJSON,
    RefIncidentsGetResponse200IncidentsFromJSONTyped,
    RefIncidentsGetResponse200IncidentsToJSON,
} from './';

/**
 * 
 * @export
 * @interface RefIncidentsGetResponse200
 */
export interface RefIncidentsGetResponse200 {
    /**
     * 
     * @type {Array<RefIncidentsGetResponse200Incidents>}
     * @memberof RefIncidentsGetResponse200
     */
    incidents: Array<RefIncidentsGetResponse200Incidents>;
}

export function RefIncidentsGetResponse200FromJSON(json: any): RefIncidentsGetResponse200 {
    return RefIncidentsGetResponse200FromJSONTyped(json, false);
}

export function RefIncidentsGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): RefIncidentsGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'incidents': ((json['incidents'] as Array<any>).map(RefIncidentsGetResponse200IncidentsFromJSON)),
    };
}

export function RefIncidentsGetResponse200ToJSON(value?: RefIncidentsGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'incidents': ((value.incidents as Array<any>).map(RefIncidentsGetResponse200IncidentsToJSON)),
    };
}


