/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev148
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Метрики датчика
 * @export
 * @interface SensorsGetResponse200Metrics
 */
export interface SensorsGetResponse200Metrics {
    /**
     * Количество активных правил датчика
     * @type {number}
     * @memberof SensorsGetResponse200Metrics
     */
    activeChecks: number;
}

export function SensorsGetResponse200MetricsFromJSON(json: any): SensorsGetResponse200Metrics {
    return SensorsGetResponse200MetricsFromJSONTyped(json, false);
}

export function SensorsGetResponse200MetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorsGetResponse200Metrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'activeChecks': json['active_checks'],
    };
}

export function SensorsGetResponse200MetricsToJSON(value?: SensorsGetResponse200Metrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active_checks': value.activeChecks,
    };
}


