/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.18.dev141
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Категория датчика
 * @export
 * @interface SensorsGetResponse200RefCategory
 */
export interface SensorsGetResponse200RefCategory {
    /**
     * Идентификатор категории
     * @type {number}
     * @memberof SensorsGetResponse200RefCategory
     */
    id: number;
    /**
     * Краткое название категории
     * @type {string}
     * @memberof SensorsGetResponse200RefCategory
     */
    name: string;
    /**
     * Категория
     * @type {string}
     * @memberof SensorsGetResponse200RefCategory
     */
    code: string;
    /**
     * Описание категории
     * @type {string}
     * @memberof SensorsGetResponse200RefCategory
     */
    description: string;
}

export function SensorsGetResponse200RefCategoryFromJSON(json: any): SensorsGetResponse200RefCategory {
    return SensorsGetResponse200RefCategoryFromJSONTyped(json, false);
}

export function SensorsGetResponse200RefCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorsGetResponse200RefCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'description': json['description'],
    };
}

export function SensorsGetResponse200RefCategoryToJSON(value?: SensorsGetResponse200RefCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'code': value.code,
        'description': value.description,
    };
}


