/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.19.dev160
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IncidentGetResponse200IncidentImageTrackBoxes,
    IncidentGetResponse200IncidentImageTrackBoxesFromJSON,
    IncidentGetResponse200IncidentImageTrackBoxesFromJSONTyped,
    IncidentGetResponse200IncidentImageTrackBoxesToJSON,
} from './';

/**
 * Превью изображения по событию
 * @export
 * @interface TimelineGetOccurrence200Thumbnail
 */
export interface TimelineGetOccurrence200Thumbnail {
    /**
     * Идентификатор категории изображения
     * @type {number}
     * @memberof TimelineGetOccurrence200Thumbnail
     */
    categoryId: number;
    /**
     * Формат изображения
     * @type {string}
     * @memberof TimelineGetOccurrence200Thumbnail
     */
    compression: string;
    /**
     * Содержимое изображения в формате Base64
     * @type {string}
     * @memberof TimelineGetOccurrence200Thumbnail
     */
    content: string;
    /**
     * Высота изображения
     * @type {number}
     * @memberof TimelineGetOccurrence200Thumbnail
     */
    height: number;
    /**
     * Идентификатор превью изображения
     * @type {number}
     * @memberof TimelineGetOccurrence200Thumbnail
     */
    id: number;
    /**
     * Идентификатор изображения
     * @type {number}
     * @memberof TimelineGetOccurrence200Thumbnail
     */
    imageId: number;
    /**
     * Разметка обнаруженных объектов
     * @type {Array<IncidentGetResponse200IncidentImageTrackBoxes>}
     * @memberof TimelineGetOccurrence200Thumbnail
     */
    trackBoxes?: Array<IncidentGetResponse200IncidentImageTrackBoxes>;
    /**
     * Ширина изображения
     * @type {number}
     * @memberof TimelineGetOccurrence200Thumbnail
     */
    width: number;
}

export function TimelineGetOccurrence200ThumbnailFromJSON(json: any): TimelineGetOccurrence200Thumbnail {
    return TimelineGetOccurrence200ThumbnailFromJSONTyped(json, false);
}

export function TimelineGetOccurrence200ThumbnailFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimelineGetOccurrence200Thumbnail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categoryId': json['category_id'],
        'compression': json['compression'],
        'content': json['content'],
        'height': json['height'],
        'id': json['id'],
        'imageId': json['image_id'],
        'trackBoxes': !exists(json, 'track_boxes') ? undefined : ((json['track_boxes'] as Array<any>).map(IncidentGetResponse200IncidentImageTrackBoxesFromJSON)),
        'width': json['width'],
    };
}

export function TimelineGetOccurrence200ThumbnailToJSON(value?: TimelineGetOccurrence200Thumbnail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'category_id': value.categoryId,
        'compression': value.compression,
        'content': value.content,
        'height': value.height,
        'id': value.id,
        'image_id': value.imageId,
        'track_boxes': value.trackBoxes === undefined ? undefined : ((value.trackBoxes as Array<any>).map(IncidentGetResponse200IncidentImageTrackBoxesToJSON)),
        'width': value.width,
    };
}


