/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.15.dev108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Сведения о событии
 * @export
 * @interface TimelineEventsGetResponse200Events
 */
export interface TimelineEventsGetResponse200Events {
    /**
     * Идентификатор площадки
     * @type {number}
     * @memberof TimelineEventsGetResponse200Events
     */
    locationId: number;
    /**
     * Идентификатор датчика
     * @type {number}
     * @memberof TimelineEventsGetResponse200Events
     */
    sensorId: number;
    /**
     * Идентификатор категории отслеживаемого объекта
     * @type {number}
     * @memberof TimelineEventsGetResponse200Events
     */
    tocId: number;
    /**
     * Код обнаруженного транспортного средства
     * @type {string}
     * @memberof TimelineEventsGetResponse200Events
     */
    trackCode: string;
    /**
     * Код события
     * @type {string}
     * @memberof TimelineEventsGetResponse200Events
     */
    eventCode: string;
    /**
     * Дата и время совершения события в формате "YYYY-MM-DD HH:MI:SS"
     * @type {string}
     * @memberof TimelineEventsGetResponse200Events
     */
    eventTimestamp: string;
    /**
     * Идентификатор категории события
     * @type {number}
     * @memberof TimelineEventsGetResponse200Events
     */
    eventTypeId: number;
}

export function TimelineEventsGetResponse200EventsFromJSON(json: any): TimelineEventsGetResponse200Events {
    return TimelineEventsGetResponse200EventsFromJSONTyped(json, false);
}

export function TimelineEventsGetResponse200EventsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimelineEventsGetResponse200Events {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'locationId': json['location_id'],
        'sensorId': json['sensor_id'],
        'tocId': json['toc_id'],
        'trackCode': json['track_code'],
        'eventCode': json['event_code'],
        'eventTimestamp': json['event_timestamp'],
        'eventTypeId': json['event_type_id'],
    };
}

export function TimelineEventsGetResponse200EventsToJSON(value?: TimelineEventsGetResponse200Events | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'location_id': value.locationId,
        'sensor_id': value.sensorId,
        'toc_id': value.tocId,
        'track_code': value.trackCode,
        'event_code': value.eventCode,
        'event_timestamp': value.eventTimestamp,
        'event_type_id': value.eventTypeId,
    };
}


