/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.15.dev108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Описание атрибута обнаруженного транспортного средства
 * @export
 * @interface TimelineEventsGetAttr
 */
export interface TimelineEventsGetAttr {
    /**
     * Код события, в котором обнаружен атрибут
     * @type {string}
     * @memberof TimelineEventsGetAttr
     */
    eventCode: string;
    /**
     * Дата и время совершения события в формате "YYYY-MM-DD HH:MI:SS"
     * @type {string}
     * @memberof TimelineEventsGetAttr
     */
    eventTimestamp: string;
    /**
     * Значение атрибута
     * @type {string}
     * @memberof TimelineEventsGetAttr
     */
    value?: string;
}

export function TimelineEventsGetAttrFromJSON(json: any): TimelineEventsGetAttr {
    return TimelineEventsGetAttrFromJSONTyped(json, false);
}

export function TimelineEventsGetAttrFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimelineEventsGetAttr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventCode': json['event_code'],
        'eventTimestamp': json['event_timestamp'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function TimelineEventsGetAttrToJSON(value?: TimelineEventsGetAttr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'event_code': value.eventCode,
        'event_timestamp': value.eventTimestamp,
        'value': value.value,
    };
}


