/* tslint:disable */
/* eslint-disable */
/**
 * va
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.15.dev108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Временной диапазон возвращаемых событий
 * @export
 * @interface TimelineEventsGetResponse200Period
 */
export interface TimelineEventsGetResponse200Period {
    /**
     * Левая граница диапазона в формате "YYYY-MM-DD HH:MI:SS"
     * @type {string}
     * @memberof TimelineEventsGetResponse200Period
     */
    startTime: string;
    /**
     * Правая граница диапазона в формате "YYYY-MM-DD HH:MI:SS"
     * @type {string}
     * @memberof TimelineEventsGetResponse200Period
     */
    endTime: string;
}

export function TimelineEventsGetResponse200PeriodFromJSON(json: any): TimelineEventsGetResponse200Period {
    return TimelineEventsGetResponse200PeriodFromJSONTyped(json, false);
}

export function TimelineEventsGetResponse200PeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimelineEventsGetResponse200Period {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startTime': json['start_time'],
        'endTime': json['end_time'],
    };
}

export function TimelineEventsGetResponse200PeriodToJSON(value?: TimelineEventsGetResponse200Period | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start_time': value.startTime,
        'end_time': value.endTime,
    };
}


