/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.9.dev48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    EventStatusesGetResponse200,
    EventStatusesGetResponse200FromJSON,
    EventStatusesGetResponse200ToJSON,
} from '../models';

/**
 * RefsApi - interface
 * 
 * @export
 * @interface RefsApiInterface
 */
export interface RefsApiInterface {
    /**
     * # 
     * @summary # Справочные сведения о статусах событий
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RefsApiInterface
     */
    apiAuthRefsEventStatusesGetRaw(): Promise<runtime.ApiResponse<EventStatusesGetResponse200>>;

    /**
     * # 
     * # Справочные сведения о статусах событий
     */
    apiAuthRefsEventStatusesGet(): Promise<EventStatusesGetResponse200>;

}

/**
 * 
 */
export class RefsApi extends runtime.BaseAPI implements RefsApiInterface {

    /**
     * # 
     * # Справочные сведения о статусах событий
     */
    async apiAuthRefsEventStatusesGetRaw(): Promise<runtime.ApiResponse<EventStatusesGetResponse200>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/auth/refs/event_statuses`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => EventStatusesGetResponse200FromJSON(jsonValue));
    }

    /**
     * # 
     * # Справочные сведения о статусах событий
     */
    async apiAuthRefsEventStatusesGet(): Promise<EventStatusesGetResponse200> {
        const response = await this.apiAuthRefsEventStatusesGetRaw();
        return await response.value();
    }

}
