/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.12.dev74
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface 
 */
export interface  {
    /**
     * Идентификатор пользователя
     * @type {number}
     * @memberof 
     */
    id: number;
    /**
     * Учетная запись пользователя
     * @type {string}
     * @memberof 
     */
    code: string;
    /**
     * Полное имя (Фамилия Имя Отчество)
     * @type {string}
     * @memberof 
     */
    fullName: string;
    /**
     * Имя
     * @type {string}
     * @memberof 
     */
    firstName: string;
    /**
     * Фамилия
     * @type {string}
     * @memberof 
     */
    lastName: string;
    /**
     * Отчество
     * @type {string}
     * @memberof 
     */
    middleName: string;
    /**
     * Краткое имя (Фамилия И.О.)
     * @type {string}
     * @memberof 
     */
    shortName: string;
    /**
     * Признак системного пользователя
     * @type {string}
     * @memberof 
     */
    system: string;
    /**
     * Адрес электронной почты
     * @type {string}
     * @memberof 
     */
    email?: string;
    /**
     * Идентификатор компании
     * @type {number}
     * @memberof 
     */
    companyId?: number;
}

export function FromJSON(json: any):  {
    return FromJSONTyped(json, false);
}

export function FromJSONTyped(json: any, ignoreDiscriminator: boolean):  {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'fullName': json['full_name'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'middleName': json['middle_name'],
        'shortName': json['short_name'],
        'system': json['system'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'companyId': !exists(json, 'company_id') ? undefined : json['company_id'],
    };
}

export function ToJSON(value?:  | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'full_name': value.fullName,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'middle_name': value.middleName,
        'short_name': value.shortName,
        'system': value.system,
        'email': value.email,
        'company_id': value.companyId,
    };
}


