/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.12.dev78
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AboutGetResponse200Resources,
    AboutGetResponse200ResourcesFromJSON,
    AboutGetResponse200ResourcesFromJSONTyped,
    AboutGetResponse200ResourcesToJSON,
} from './';

/**
 * Сведения о сервисе и API
 * @export
 * @interface AboutGetResponse200
 */
export interface AboutGetResponse200 {
    /**
     * Идентификатор последнего коммита
     * @type {string}
     * @memberof AboutGetResponse200
     */
    commit: string;
    /**
     * Название среды
     * @type {string}
     * @memberof AboutGetResponse200
     */
    env: string;
    /**
     * Название сервиса
     * @type {string}
     * @memberof AboutGetResponse200
     */
    name: string;
    /**
     * Методы API
     * @type {Array<AboutGetResponse200Resources>}
     * @memberof AboutGetResponse200
     */
    resources: Array<AboutGetResponse200Resources>;
    /**
     * Дата и время сборки
     * @type {string}
     * @memberof AboutGetResponse200
     */
    timestamp: string;
    /**
     * Версия API
     * @type {string}
     * @memberof AboutGetResponse200
     */
    version: string;
}

export function AboutGetResponse200FromJSON(json: any): AboutGetResponse200 {
    return AboutGetResponse200FromJSONTyped(json, false);
}

export function AboutGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): AboutGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commit': json['commit'],
        'env': json['env'],
        'name': json['name'],
        'resources': ((json['resources'] as Array<any>).map(AboutGetResponse200ResourcesFromJSON)),
        'timestamp': json['timestamp'],
        'version': json['version'],
    };
}

export function AboutGetResponse200ToJSON(value?: AboutGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'commit': value.commit,
        'env': value.env,
        'name': value.name,
        'resources': ((value.resources as Array<any>).map(AboutGetResponse200ResourcesToJSON)),
        'timestamp': value.timestamp,
        'version': value.version,
    };
}


