/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.9.dev54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Описание категории
 * @export
 * @interface CheckCategoriesGetResponse200
 */
export interface CheckCategoriesGetResponse200 {
    /**
     * Идентификатор категории
     * @type {number}
     * @memberof CheckCategoriesGetResponse200
     */
    id: number;
    /**
     * Код категории
     * @type {string}
     * @memberof CheckCategoriesGetResponse200
     */
    code: string;
    /**
     * Краткое название категории
     * @type {string}
     * @memberof CheckCategoriesGetResponse200
     */
    name: string;
    /**
     * Описание категории
     * @type {string}
     * @memberof CheckCategoriesGetResponse200
     */
    description: string;
}

export function CheckCategoriesGetResponse200FromJSON(json: any): CheckCategoriesGetResponse200 {
    return CheckCategoriesGetResponse200FromJSONTyped(json, false);
}

export function CheckCategoriesGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckCategoriesGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function CheckCategoriesGetResponse200ToJSON(value?: CheckCategoriesGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'name': value.name,
        'description': value.description,
    };
}


