/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.12.dev77
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CheckCategoriesGetResponse200Categories,
    CheckCategoriesGetResponse200CategoriesFromJSON,
    CheckCategoriesGetResponse200CategoriesFromJSONTyped,
    CheckCategoriesGetResponse200CategoriesToJSON,
} from './';

/**
 * 
 * @export
 * @interface CheckCategoriesGetResponse200
 */
export interface CheckCategoriesGetResponse200 {
    /**
     * 
     * @type {Array<CheckCategoriesGetResponse200Categories>}
     * @memberof CheckCategoriesGetResponse200
     */
    categories: Array<CheckCategoriesGetResponse200Categories>;
}

export function CheckCategoriesGetResponse200FromJSON(json: any): CheckCategoriesGetResponse200 {
    return CheckCategoriesGetResponse200FromJSONTyped(json, false);
}

export function CheckCategoriesGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckCategoriesGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categories': ((json['categories'] as Array<any>).map(CheckCategoriesGetResponse200CategoriesFromJSON)),
    };
}

export function CheckCategoriesGetResponse200ToJSON(value?: CheckCategoriesGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categories': ((value.categories as Array<any>).map(CheckCategoriesGetResponse200CategoriesToJSON)),
    };
}


