/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.12.dev76
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Описание проверки
 * @export
 * @interface ChecksGetResponse200Checks
 */
export interface ChecksGetResponse200Checks {
    /**
     * Идентификатор проверки
     * @type {number}
     * @memberof ChecksGetResponse200Checks
     */
    id: number;
    /**
     * Код проверки
     * @type {string}
     * @memberof ChecksGetResponse200Checks
     */
    code: string;
    /**
     * Краткое название проверки
     * @type {string}
     * @memberof ChecksGetResponse200Checks
     */
    name: string;
    /**
     * Описание проверки
     * @type {string}
     * @memberof ChecksGetResponse200Checks
     */
    description: string;
    /**
     * Идентификатор категории проверки
     * @type {number}
     * @memberof ChecksGetResponse200Checks
     */
    categoryId: number;
}

export function ChecksGetResponse200ChecksFromJSON(json: any): ChecksGetResponse200Checks {
    return ChecksGetResponse200ChecksFromJSONTyped(json, false);
}

export function ChecksGetResponse200ChecksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChecksGetResponse200Checks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'description': json['description'],
        'categoryId': json['category_id'],
    };
}

export function ChecksGetResponse200ChecksToJSON(value?: ChecksGetResponse200Checks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'name': value.name,
        'description': value.description,
        'category_id': value.categoryId,
    };
}


