/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.9.dev57
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EventStatusesGetResponse200EventStatuses,
    EventStatusesGetResponse200EventStatusesFromJSON,
    EventStatusesGetResponse200EventStatusesFromJSONTyped,
    EventStatusesGetResponse200EventStatusesToJSON,
} from './';

/**
 *
 * @export
 * @interface DetectorsGetResponse200
 */
export interface DetectorsGetResponse200 {
    /**
     *
     * @type {Array<EventStatusesGetResponse200EventStatuses>}
     * @memberof EventStatusesGetResponse200
     */
    eventStatuses: Array<EventStatusesGetResponse200EventStatuses>;
}

export function DetectorsGetResponse200FromJSON(json: any): DetectorsGetResponse200 {
    return DetectorsGetResponse200FromJSONTyped(json, false);
}

export function DetectorsGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectorsGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'eventStatuses': ((json['event_statuses'] as Array<any>).map(EventStatusesGetResponse200EventStatusesFromJSON)),
    };
}

export function DetectorsGetResponse200ToJSON(value?: DetectorsGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'event_statuses': ((value.eventStatuses as Array<any>).map(EventStatusesGetResponse200EventStatusesToJSON)),
    };
}


