/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.9.dev48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Статус по событию
 * @export
 * @interface EventStatusesGetResponse200
 */
export interface EventStatusesGetResponse200 {
    /**
     * Идентификатор статуса
     * @type {number}
     * @memberof EventStatusesGetResponse200
     */
    id: number;
    /**
     * Код статуса
     * @type {string}
     * @memberof EventStatusesGetResponse200
     */
    code: string;
    /**
     * Краткое название статуса
     * @type {string}
     * @memberof EventStatusesGetResponse200
     */
    name: string;
    /**
     * Описание статуса
     * @type {string}
     * @memberof EventStatusesGetResponse200
     */
    description: string;
}

export function EventStatusesGetResponse200FromJSON(json: any): EventStatusesGetResponse200 {
    return EventStatusesGetResponse200FromJSONTyped(json, false);
}

export function EventStatusesGetResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): EventStatusesGetResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function EventStatusesGetResponse200ToJSON(value?: EventStatusesGetResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'name': value.name,
        'description': value.description,
    };
}


