/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Токен доступа
 * @export
 * @interface LoginPostToken
 */
export interface LoginPostToken {
    /**
     * Значение токена доступа
     * @type {string}
     * @memberof LoginPostToken
     */
    value: string;
    /**
     * Дата и время истечения срока действия
     * @type {string}
     * @memberof LoginPostToken
     */
    expiredAt: string;
}

export function LoginPostTokenFromJSON(json: any): LoginPostToken {
    return LoginPostTokenFromJSONTyped(json, false);
}

export function LoginPostTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginPostToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'expiredAt': json['expired_at'],
    };
}

export function LoginPostTokenToJSON(value?: LoginPostToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'expired_at': value.expiredAt,
    };
}


