/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.12.dev78
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StatusChainsGetResponse200Chain,
    StatusChainsGetResponse200ChainFromJSON,
    StatusChainsGetResponse200ChainFromJSONTyped,
    StatusChainsGetResponse200ChainToJSON,
    StatusChainsGetResponse200Relations,
    StatusChainsGetResponse200RelationsFromJSON,
    StatusChainsGetResponse200RelationsFromJSONTyped,
    StatusChainsGetResponse200RelationsToJSON,
} from './';

/**
 * Сведения о цепочке статусов
 * @export
 * @interface StatusChainsGetResponse200Chains
 */
export interface StatusChainsGetResponse200Chains {
    /**
     * 
     * @type {StatusChainsGetResponse200Chain}
     * @memberof StatusChainsGetResponse200Chains
     */
    chain: StatusChainsGetResponse200Chain;
    /**
     * Переход между статусами в цепочки статусов
     * @type {Array<StatusChainsGetResponse200Relations>}
     * @memberof StatusChainsGetResponse200Chains
     */
    relations: Array<StatusChainsGetResponse200Relations>;
    /**
     * Перечень идентификаторов статусов, входящих в цепочку статусов
     * @type {Array<number>}
     * @memberof StatusChainsGetResponse200Chains
     */
    statusIds: Array<number>;
}

export function StatusChainsGetResponse200ChainsFromJSON(json: any): StatusChainsGetResponse200Chains {
    return StatusChainsGetResponse200ChainsFromJSONTyped(json, false);
}

export function StatusChainsGetResponse200ChainsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusChainsGetResponse200Chains {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chain': StatusChainsGetResponse200ChainFromJSON(json['chain']),
        'relations': ((json['relations'] as Array<any>).map(StatusChainsGetResponse200RelationsFromJSON)),
        'statusIds': json['status_ids'],
    };
}

export function StatusChainsGetResponse200ChainsToJSON(value?: StatusChainsGetResponse200Chains | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chain': StatusChainsGetResponse200ChainToJSON(value.chain),
        'relations': ((value.relations as Array<any>).map(StatusChainsGetResponse200RelationsToJSON)),
        'status_ids': value.statusIds,
    };
}


