/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenPostToken
 */
export interface TokenPostToken {
    /**
     * Значение токена доступа
     * @type {string}
     * @memberof TokenPostToken
     */
    value: string;
    /**
     * Дата и время истечения срока действия токена
     * @type {string}
     * @memberof TokenPostToken
     */
    expiredAt: string;
}

export function TokenPostTokenFromJSON(json: any): TokenPostToken {
    return TokenPostTokenFromJSONTyped(json, false);
}

export function TokenPostTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenPostToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'expiredAt': json['expired_at'],
    };
}

export function TokenPostTokenToJSON(value?: TokenPostToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'expired_at': value.expiredAt,
    };
}


