/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  LoginPostResponse201User,
  TokenPostToken,
  TokenPostTokenFromJSON,
} from './';

/**
 *
 * @export
 * @interface TokenPostResponse201
 */
export interface TokenPostResponse201 {
  /**
   *
   * @type {}
   * @memberof TokenPostResponse201
   */
  user: LoginPostResponse201User;
  /**
   *
   * @type {TokenPostToken}
   * @memberof TokenPostResponse201
   */
  accessToken: TokenPostToken;
}

export function TokenPostResponse201FromJSON(json: any): TokenPostResponse201 {
  return TokenPostResponse201FromJSONTyped(json, false);
}

export function TokenPostResponse201FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TokenPostResponse201 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: json['user'],
    accessToken: TokenPostTokenFromJSON(json['access_token']),
  };
}
