/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.9.dev48
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TokenPostToken,
    TokenPostTokenFromJSON,
    TokenPostTokenFromJSONTyped,
    TokenPostTokenToJSON,
    LoginPostResponse201User,
    LoginPostResponse201UserFromJSON,
    LoginPostResponse201UserToJSON
} from './';

/**
 *
 * @export
 * @interface TokenPostResponse201
 */
export interface TokenPostResponse201 {
    /**
     *
     * @type {}
     * @memberof TokenPostResponse201
     */
    user: LoginPostResponse201User;
    /**
     *
     * @type {TokenPostToken}
     * @memberof TokenPostResponse201
     */
    accessToken: TokenPostToken;
}

export function TokenPostResponse201FromJSON(json: any): TokenPostResponse201 {
    return TokenPostResponse201FromJSONTyped(json, false);
}

export function TokenPostResponse201FromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenPostResponse201 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'user': LoginPostResponse201UserFromJSON(json['user']),
        'accessToken': TokenPostTokenFromJSON(json['access_token']),
    };
}

export function TokenPostResponse201ToJSON(value?: TokenPostResponse201 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'user': LoginPostResponse201UserToJSON(value.user),
        'access_token': TokenPostTokenToJSON(value.accessToken),
    };
}


